apiVersion: v1
kind: ReplicationController
metadata:
  name: guestbook
  labels:
    name: guestbook
spec:
  replicas: 1
  selector:
    name: guestbook
  template:
    metadata:
      labels:
        name: guestbook
    spec:
      containers:
      - name: python-guestbook
        image: google/guestbook-python-redis
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: ".5Gi"
            cpu: "25m"
          limits:
            memory: "1Gi"
            cpu: "50m"
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: ".5Gi"
            cpu: "25m"
          limits:
            memory: "1Gi"
            cpu: "50m"
