apiVersion: v1
kind: ReplicationController
metadata:
  name: guestbook
  labels:
    name: guestbook
spec:
  replicas: 1
  selector:
    name: guestbook
  template:
    metadata:
      labels:
        name: guestbook
    spec:
      containers:
      - name: python-guestbook
        image: google/guestbook-python-redis
        ports:
        - containerPort: 80
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
